# Generated by Django 3.0.7 on 2020-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': '도서관 사용자'},
        ),
        migrations.AddField(
            model_name='users',
            name='useremail',
            field=models.EmailField(default='test@test.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
