# Generated by Django 3.0.7 on 2020-06-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200625_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(verbose_name='검색한 책')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='검색한 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검색한 사용자')),
            ],
        ),
    ]
